SET SCHEMA ML_TEXT;
-- Bei zweiter Ausführung: Tabelle vorher löschen
-- DROP TABLE PAL_LDA_PARAMETER_TBL;

CREATE COLUMN TABLE PAL_LDA_PARAMETER_TBL (
    "PARAM_NAME" VARCHAR(256),
    "INT_VALUE" INTEGER,
    "DOUBLE_VALUE" DOUBLE,
    "STRING_VALUE" VARCHAR(1000));

-- Pflichtparameter
INSERT INTO PAL_LDA_PARAMETER_TBL VALUES (
    'TOPICS', 10, NULL, NULL);

-- Optionale Parameter
-- Alternativ zu MAX_TOP_WORDS: Angabe THRESHOLD_TOP_WORDS
INSERT INTO PAL_LDA_PARAMETER_TBL VALUES (
    'MAX_TOP_WORDS', 10, NULL, NULL);

-- Initialisierung Zufallsgenerator
INSERT INTO PAL_LDA_PARAMETER_TBL VALUES (
    'SEED', 42, NULL, NULL);

INSERT INTO PAL_LDA_PARAMETER_TBL VALUES(
    'OUTPUT_WORD_ASSIGNMENT', 1, NULL, NULL);
