SET SESSION 'APL_CACHE_SCHEMA' = 'APL_CACHE';
SET SCHEMA ML_APL;

-- Bei zweitem Aufruf: Erst Tabellen löschen
-- DROP TABLE ML_APL.FUNC_HEADER;
-- DROP TABLE ML_APL.PROFILE_DATA_CONFIG;
-- DROP TABLE VARIABLE_ROLES;
-- DROP TABLE VARIABLE_DESC;

CREATE TABLE FUNC_HEADER LIKE "SAP_PA_APL"."sap.pa.apl.base::BASE.T.FUNCTION_HEADER";
INSERT INTO FUNC_HEADER VALUES ('Oid', '#42');
INSERT INTO FUNC_HEADER VALUES ('LogLevel', '8');

CREATE TABLE PROFILE_DATA_CONFIG LIKE "SAP_PA_APL"."sap.pa.apl.base::BASE.T.OPERATION_CONFIG_EXTENDED";
CREATE TABLE VARIABLE_ROLES LIKE "SAP_PA_APL"."sap.pa.apl.base::BASE.T.VARIABLE_ROLES_WITH_COMPOSITES_OID";
CREATE TABLE VARIABLE_DESC LIKE "SAP_PA_APL"."sap.pa.apl.base::BASE.T.VARIABLE_DESC_OID";
