CREATE SCHEMA ML_DATA;
CREATE SCHEMA ML_APL;
CREATE SCHEMA APL_CACHE;
CREATE SCHEMA ML_MODEL;

-- Beispieltabellen für Daten in Schema ML_DATA anlegen

SET SCHEMA ML_DATA;
-- Table CHURN 
CREATE COLUMN TABLE "CHURN" ("ROWNUMBER" INTEGER CS_INT COMMENT ' ',
	 "CUSTOMERID" INTEGER CS_INT COMMENT ' ',
	 "SURNAME" NVARCHAR(50) COMMENT ' ',
	 "CREDITSCORE" INTEGER CS_INT COMMENT ' ',
	 "GEOGRAPHY" NVARCHAR(100) COMMENT ' ',
	 "GENDER" NVARCHAR(10) COMMENT ' ',
	 "AGE" INTEGER CS_INT COMMENT ' ',
	 "TENURE" INTEGER CS_INT COMMENT ' ',
	 "BALANCE" DOUBLE CS_DOUBLE COMMENT ' ',
	 "NUMOFPRODUCTS" INTEGER CS_INT COMMENT ' ',
	 "HASCRCARD" INTEGER CS_INT COMMENT ' ',
	 "ISACTIVEMEMBER" INTEGER CS_INT COMMENT ' ',
	 "ESTIMATEDSALARY" DOUBLE CS_DOUBLE COMMENT ' ',
	 "EXITED" INTEGER CS_INT COMMENT ' ') UNLOAD PRIORITY 5 AUTO MERGE 


-- Table IRIS
CREATE COLUMN TABLE "IRIS" ("PLANTID" INTEGER CS_INT NOT NULL COMMENT ' ',
	 "SEPAL_LENGTH" DOUBLE CS_DOUBLE COMMENT ' ',
	 "SEPAL_WIDTH" DOUBLE CS_DOUBLE COMMENT ' ',
	 "PETAL_LENGTH" DOUBLE CS_DOUBLE COMMENT ' ',
	 "PETAL_WIDTH" DOUBLE CS_DOUBLE COMMENT ' ',
	 "SPECIES" NVARCHAR(10) COMMENT ' ',
	 PRIMARY KEY ("PLANTID")) UNLOAD PRIORITY 5 AUTO MERGE 

-- Table CUSTOMER_MALL
CREATE COLUMN TABLE "MALL_CUSTOMERS" ("CUSTOMERID" INTEGER CS_INT,
	 "GENDER" VARCHAR(10),
	 "AGE" INTEGER CS_INT,
	 "INCOME" INTEGER CS_INT,
	 "SPENDINGSCORE" INTEGER CS_INT) UNLOAD PRIORITY 5 AUTO MERGE 

-- Table DWD_HOUR
CREATE COLUMN TABLE "DWD_HOUR" ("SDO_ID" SMALLINT CS_INT COMMENT ' ',
	 "TIMESTAMP" BIGINT CS_FIXED COMMENT ' ',
	 "VALUE" DOUBLE CS_DOUBLE COMMENT ' ') UNLOAD PRIORITY 5 AUTO MERGE 


-- Spezifische Rolle für die drei Schemata: ML_BOOK_ROLE
CREATE ROLE ROLE_ML_BOOK_SCHEMA;
GRANT CREATE ANY ON SCHEMA ML_DATA TO ROLE_ML_BOOK_SCHEMA;
GRANT CREATE ANY ON SCHEMA ML_APL TO ROLE_ML_BOOK_SCHEMA;
GRANT CREATE ANY ON SCHEMA ML_MODEL TO ROLE_ML_BOOK_SCHEMA;

-- Der Ersteller der Schemata hat automatisch diese Berechtigungen
-- Um die Berechtigungen an andere Nutzer zu vergeben:
-- GRANT ROLE_ML_BOOK_SCHEMA TO <USER>


