-- Ab zweitem Durchlauf: Tabellen vorher löschen
-- DROP TABLE CHURN_TRAIN;
-- DROP TABLE CHURN_TEST;

DO BEGIN

-- Modus: Zufallswahl
lt_id_train = SELECT TOP 2000 CUSTOMERID FROM ML_DATA.CHURN
    ORDER BY rand();

CREATE TABLE CHURN_TRAIN AS (SELECT * FROM ML_DATA.CHURN
    WHERE EXISTS 
        (SELECT CUSTOMERID FROM :lt_id_train WHERE
         CUSTOMERID = CHURN.CUSTOMERID));

CREATE TABLE CHURN_TEST AS (SELECT * FROM ML_DATA.CHURN
    WHERE NOT EXISTS 
        (SELECT CUSTOMERID FROM :lt_id_train WHERE
        CUSTOMERID = CHURN.CUSTOMERID));
END;
