-- Kapitel Textmining - Vorbereitung

-- Schema ML_TEXT erstellen und Tabelle für NEWS

CREATE SCHEMA ML_TEXT;

-- Bei erneutem Import => vorher Tabellen löschen
-- DROP TABLE ML_TEXT.NEWSCORP;
-- DROP TABLE ML_TEXT.NEWSCORP_RAW;

CREATE COLUMN TABLE ML_TEXT.NEWSCORP ( 
KEY INT generated by default as identity PRIMARY KEY,
CATEGORY nvarchar(20),
TEXT clob );

CREATE COLUMN TABLE ML_TEXT.NEWSCORP_RAW ( 
CATEGORY nvarchar(20),
TEXT clob );