-- Vorbereiten der Parameter-Tabelle
-- Einfügen in Quellcode aus Listing 2.2 vor END

CREATE LOCAL TEMPORARY COLUMN TABLE
    #PAL_PARAMETER_TBL(
        NAME VARCHAR (50),
        INT_VALUE INTEGER,
        DOUBLE_VALUE DOUBLE,
        STRING_VALUE VARCHAR (100));

INSERT INTO #PAL_PARAMETER_TBL VALUES
    ('ALGORITHM', 1, NULL, NULL); 
INSERT INTO #PAL_PARAMETER_TBL VALUES
    ('HAS_ID', 1, NULL, NULL);

INSERT INTO #PAL_PARAMETER_TBL VALUES
    ('CATEGORICAL_VARIABLE', NULL, NULL, 'EXITED');
INSERT INTO #PAL_PARAMETER_TBL VALUES
    ('CATEGORICAL_VARIABLE', NULL, NULL, 'HASCRCARD');
INSERT INTO #PAL_PARAMETER_TBL VALUES
    ('CATEGORICAL_VARIABLE', NULL, NULL, 'ISACTIVEMEMBER');

lt_parameter_tbl = SELECT * FROM #PAL_PARAMETER_TBL;

-- Optional: Ausgabe der Parameter-Tabelle
-- SELECT * FROM :lt_parameter_tbl;



